# Generated by Django 3.0.4 on 2020-03-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_ingredienttag_description'),
        ('products', '0003_auto_20190128_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient'),
        ),
    ]
