# Generated by Django 3.0.4 on 2020-03-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_price_ingredient_attach_20200319_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
    ]
