# Generated by Django 3.0.4 on 2020-03-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_ingredienttag_description'),
        ('products', '0006_remove_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient'),
        ),
    ]
