# Generated by Django 2.0.1 on 2018-01-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_auto_20180130_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrients',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Nutrients',
        ),
    ]
