# Generated by Django 2.0.1 on 2018-01-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_auto_20180130_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-updated_at']},
        ),
    ]
