# Generated by Django 2.1.5 on 2019-04-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_auto_20180331_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttag',
            name='name',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
