# Generated by Django 3.0.2 on 2020-03-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_auto_20190405_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttag',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
