# Generated by Django 3.0.4 on 2020-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_ingredienttag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
