# Generated by Django 3.0.4 on 2020-03-19 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('recipes', '0001_initial'), ('recipes', '0002_auto_20170709_0757'), ('recipes', '0003_recipe_serves'), ('recipes', '0004_auto_20170710_1410'), ('recipes', '0005_auto_20170713_0553'), ('recipes', '0006_auto_20170713_1548'), ('recipes', '0007_component'), ('recipes', '0008_auto_20170714_0331'), ('recipes', '0009_auto_20170715_1454'), ('recipes', '0010_auto_20170715_1657'), ('recipes', '0011_auto_20170717_2308'), ('recipes', '0012_auto_20180130_1856'), ('recipes', '0013_auto_20180403_1541'), ('recipes', '0014_remove_component_of_product'), ('recipes', '0015_auto_20190908_0022'), ('recipes', '0016_auto_20190908_0042'), ('recipes', '0017_auto_20190908_0136')]

    initial = True

    dependencies = [
        ('ingredients', '0001_squashed_0008_auto_20180130_1455'),
        ('products', '0002_auto_20170713_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('method', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serves', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.ManyToManyField(blank=True, to='recipes.RecipeTag')),
                ('last_tested', models.DateTimeField(blank=True, help_text='When this recipe was last made to check it works, and it did', null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='In grams; WARNING will be overridden by servings if that is used', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='ingredients.Ingredient')),
                ('of_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='recipes.Recipe')),
                ('in_recipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipes.Recipe')),
                ('servings', models.DecimalField(blank=True, decimal_places=2, help_text='WARNING: Overrides weight if used!', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
