# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
