# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170710_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
