# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20170713_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
