# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20170714_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='g or ml for ingredients or products; number of serves for recipes', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
