# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 16:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20170715_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='amount',
            field=models.DecimalField(decimal_places=3, help_text='g or ml for ingredients or products; number of serves for recipes', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
