# Generated by Django 2.0.1 on 2018-01-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20170717_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='component',
            name='of_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='ingredients.Ingredient'),
        ),
        migrations.AlterField(
            model_name='component',
            name='of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='component',
            name='of_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='recipes.Recipe'),
        ),
    ]
