# Generated by Django 2.0.1 on 2018-04-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20180130_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='amount',
            new_name='weight',
        ),
    ]
