# Generated by Django 2.1.5 on 2019-04-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20180403_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='of_product',
        ),
    ]
