# Generated by Django 2.2.1 on 2019-09-07 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_component_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_tested',
            field=models.DateTimeField(blank=True, help_text='When this recipe was last made to check it works, and it did', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='grams for ingredients; number of serves for recipes', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
