# Generated by Django 2.2.1 on 2019-09-07 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20190908_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='servings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='WARNING: Overrides weight if used!', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='component',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='In grams; WARNING will be overridden by servings if that is used', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
