# Generated by Django 2.2.1 on 2019-09-07 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20190908_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In grams; WARNING will be overridden by servings if that is used', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
