# Generated by Django 2.2.1 on 2019-09-07 15:52

from django.db import migrations


def convert_weight_servings(apps, schema_editor):
   # For all components which have a recipe but not specified in
   # servings, move the value stored in weight into servings and
   # calculate the correct weight from the servings.

   Recipe = apps.get_model('recipes','Recipe')
   rqset = Recipe.objects.filter(components__of_recipe__isnull=False)

   for rec in rqset.iterator():
      for comp in rec.components.iterator():
         if comp.of_recipe and comp.servings is None:
            # This Component has the number of serves of the recipe
            # stored in the weight column - convert to use new field
            comp.servings = comp.weight
            comp.weight = None
            # Above should not cause KeyError unless the Recipe/Component is corrupt
            comp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20190908_0136'),
    ]

    operations = [
       migrations.RunPython(convert_weight_servings),
    ]
