# Generated by Django 3.0.2 on 2020-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20190908_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
