# Generated by Django 2.0.1 on 2018-01-30 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryfood',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, help_text='g or ml for ingredients or products; number of serves for recipes', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryfood',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the entry i.e. description of the food', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='diaryfood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
