# Generated by Django 2.0.1 on 2018-01-30 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20180130_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryfood',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
