# Generated by Django 2.0.1 on 2018-02-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180201_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryfood',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the entry i.e. description of the food', max_length=100),
        ),
    ]
