# Generated by Django 2.0.1 on 2018-03-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20180312_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryfood',
            old_name='amount',
            new_name='weight',
        ),
    ]
