# Generated by Django 2.0.1 on 2018-03-31 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20180331_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryfood',
            name='serves',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='number of serves for recipes or ingredients - this will determine weight automatically', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='diaryfood',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='g or ml for ingredients or products; using serves will OVERWRITE this value!', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
