# Generated by Django 2.0.1 on 2018-03-31 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20180331_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryfood',
            name='serves',
        ),
        migrations.AddField(
            model_name='diaryfood',
            name='servings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='number of servings for recipes or ingredients - WARNING: entering this will overwrite weight & cost automatically', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='diaryfood',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='g or ml for ingredients or products; WARNING: using servings will OVERWRITE this value!', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
