# Generated by Django 3.0.4 on 2020-03-19 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20180331_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryfood',
            name='of_product',
        ),
        migrations.AlterField(
            model_name='diaryfood',
            name='servings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='number of servings of a recipe/ingredient- WARNING: entering this will overwrite weight & cost automatically', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='diaryfood',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='grams of a recipe/ingredient; WARNING: using servings will OVERWRITE this value!', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
